source 'https://github.com/CocoaPods/Specs.git'

# --- 关键：必须 load 脚本生成的 helper ---
podhelper_path = File.join(__dir__, 'Flutter', 'podhelper.rb')
load podhelper_path if File.exist?(podhelper_path)

platform :ios, '13.0' # 建议统一 13.0

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  # 阿里原生库
  pod 'AlivcLivePusher_Interactive', '6.17.0'

  # 插件自动关联（调用 podhelper.rb 里的函数）
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/../Flutter/Fix" '
        # 增加这一行，防止非模块化头文件报错
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end

  # 你的 GeneratedPluginRegistrant 补丁
  reg_m = File.join(Dir.pwd, 'Runner', 'GeneratedPluginRegistrant.m')
  if File.exist?(reg_m)
    content = File.read(reg_m)
    if content.include?('@import flutter_livepush_plugin;')
      content.gsub!('@import flutter_livepush_plugin;', '#import "AlivcLivePusherPlugin.h"')
      File.open(reg_m, 'w') { |f| f.write(content) }
    end
  end
end